=== huracanon-netizen/Grupo7-RaulCalves-Mario-Aaron/src/desafío_LM/datos/DTD/viajes.dtd
<!ELEMENT viajes (viaje+)>

<!ELEMENT viaje (destino, precio, dias, tipo, personas, imagen, hotel, vuelo, comidas, guia)>

<!ELEMENT destino (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT dias (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT personas (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT hotel (#PCDATA)>
<!ELEMENT vuelo (#PCDATA)>
<!ELEMENT comidas (#PCDATA)>
<!ELEMENT guia (#PCDATA)>

=== huracanon-netizen/Grupo7-RaulCalves-Mario-Aaron/src/desafío_LM/datos/XML/viajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE viajes SYSTEM "../DTD/viajes.dtd">

<!-- Archivo XML que contiene el catálogo de viajes -->
<!-- Se utiliza para cargar datos dinámicamente en la web -->
<viajes>
    <viaje>
        <destino>Paris 1</destino>
        <precio>330</precio>
        <dias>2</dias>
        <tipo>Romantico</tipo>
        <personas>1</personas>
        <imagen>paris.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Paris 2</destino>
        <precio>990</precio>
        <dias>3</dias>
        <tipo>Romantico</tipo>
        <personas>2</personas>
        <imagen>paris.jpg</imagen>
        <hotel>3 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno/Merienda/Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Paris 3</destino>
        <precio>660</precio>
        <dias>2</dias>
        <tipo>Romantico</tipo>
        <personas>2</personas>
        <imagen>paris.jpg</imagen>
        <hotel>5 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Paris 4</destino>
        <precio>2640</precio>
        <dias>4</dias>
        <tipo>Romantico</tipo>
        <personas>4</personas>
        <imagen>paris.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Paris 5</destino>
        <precio>165</precio>
        <dias>1</dias>
        <tipo>Romantico</tipo>
        <personas>1</personas>
        <imagen>paris.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Paris 6</destino>
        <precio>2310</precio>
        <dias>7</dias>
        <tipo>Romantico</tipo>
        <personas>2</personas>
        <imagen>paris.jpg</imagen>
        <hotel>5 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno/Merienda/Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Paris 7</destino>
        <precio>660</precio>
        <dias>2</dias>
        <tipo>Romantico</tipo>
        <personas>2</personas>
        <imagen>paris.jpg</imagen>
        <hotel>2 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno/Merienda/Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Paris 8</destino>
        <precio>1160</precio>
        <dias>4</dias>
        <tipo>Romantico</tipo>
        <personas>2</personas>
        <imagen>paris.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Comidas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Paris 9</destino>
        <precio>660</precio>
        <dias>2</dias>
        <tipo>Romantico</tipo>
        <personas>2</personas>
        <imagen>paris.jpg</imagen>
        <hotel>3 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Paris 10</destino>
        <precio>4620</precio>
        <dias>14</dias>
        <tipo>Romantico</tipo>
        <personas>2</personas>
        <imagen>paris.jpg</imagen>
        <hotel>5 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Comidas</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Paris 11</destino>
        <precio>870</precio>
        <dias>6</dias>
        <tipo>Romantico</tipo>
        <personas>1</personas>
        <imagen>paris.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Tokio 1</destino>
        <precio>480</precio>
        <dias>2</dias>
        <tipo>Aventura</tipo>
        <personas>1</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Cenas</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Tokio 2</destino>
        <precio>960</precio>
        <dias>2</dias>
        <tipo>Aventura</tipo>
        <personas>2</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno/Merienda/Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Tokio 3</destino>
        <precio>720</precio>
        <dias>3</dias>
        <tipo>Aventura</tipo>
        <personas>1</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Tokio 4</destino>
        <precio>240</precio>
        <dias>1</dias>
        <tipo>Aventura</tipo>
        <personas>1</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Comidas</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Tokio 5</destino>
        <precio>2160</precio>
        <dias>3</dias>
        <tipo>Aventura</tipo>
        <personas>3</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Tokio 6</destino>
        <precio>720</precio>
        <dias>3</dias>
        <tipo>Aventura</tipo>
        <personas>1</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Comidas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Tokio 7</destino>
        <precio>3360</precio>
        <dias>7</dias>
        <tipo>Aventura</tipo>
        <personas>2</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno/Merienda/Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Tokio 8</destino>
        <precio>720</precio>
        <dias>3</dias>
        <tipo>Aventura</tipo>
        <personas>1</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>2 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Tokio 9</destino>
        <precio>240</precio>
        <dias>1</dias>
        <tipo>Aventura</tipo>
        <personas>1</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>3 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Cenas</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Tokio 10</destino>
        <precio>4800</precio>
        <dias>5</dias>
        <tipo>Aventura</tipo>
        <personas>4</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>3 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno/Merienda/Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Tokio 11</destino>
        <precio>720</precio>
        <dias>3</dias>
        <tipo>Aventura</tipo>
        <personas>1</personas>
        <imagen>tokio.jpg</imagen>
        <hotel>3 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Roma 1</destino>
        <precio>145</precio>
        <dias>1</dias>
        <tipo>Cultural</tipo>
        <personas>1</personas>
        <imagen>roma.jpg</imagen>
        <hotel>5 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Comidas</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Roma 2</destino>
        <precio>1160</precio>
        <dias>4</dias>
        <tipo>Cultural</tipo>
        <personas>2</personas>
        <imagen>roma.jpg</imagen>
        <hotel>5 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Roma 3</destino>
        <precio>290</precio>
        <dias>1</dias>
        <tipo>Cultural</tipo>
        <personas>2</personas>
        <imagen>roma.jpg</imagen>
        <hotel>5 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Comidas</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Roma 4</destino>
        <precio>870</precio>
        <dias>3</dias>
        <tipo>Cultural</tipo>
        <personas>2</personas>
        <imagen>roma.jpg</imagen>
        <hotel>3 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno/Merienda/Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Roma 5</destino>
        <precio>1740</precio>
        <dias>7</dias>
        <tipo>Cultural</tipo>
        <personas>3</personas>
        <imagen>roma.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Comidas</comidas>
        <guia>No</guia>
    </viaje>
    <viaje>
        <destino>Roma 6</destino>
        <precio>3045</precio>
        <dias>4</dias>
        <tipo>Cultural</tipo>
        <personas>2</personas>
        <imagen>roma.jpg</imagen>
        <hotel>3 estrellas</hotel>
        <vuelo>Incluido</vuelo>
        <comidas>Desayuno/Merienda/Cenas</comidas>
        <guia>Si</guia>
    </viaje>
    <viaje>
        <destino>Roma 7</destino>
        <precio>510</precio>
        <dias>4</dias>
        <tipo>Cultural</tipo>
        <personas>1</personas>
        <imagen>roma.jpg</imagen>
        <hotel>4 estrellas</hotel>
        <vuelo>Incluido</vuelo>
